server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/price_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/baseChangelog.xml
    default-schema: public
  kafka:
    bootstrap-servers: localhost:9092
