server:
  port: 8080

price-collector:
  scheduler:
    cron: "0 */1 * * * *"

spring:
  application:
    name: price-collector-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-interval: 10s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

core:
  url: http://localhost:8081/api
