server:
  port: 8082

price-notifier:
  scheduler:
    cron: "0 0 */6 * * *"

spring:
  application:
    name: price-notifier-service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-interval: 10s
      config:
        enabled: true
        prefix: config
        default-context: price-notifier
        format: YAML
        data-key: data

core:
  url: http://localhost:8081/api
